### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by ncovgt2020** [ThisIsIsaac/COVID-19_Korea_Dataset#11]
Hi,

My question is non-related to the dataset you are collecting, but I was wondering if, in the process of collecting this data, have you met an X-RAY or CT (computerized tomography) image dataset from South Korea? If you know of such a project or point me where to ask, it would be extremelly helpful to other projects like [this](https://github.com/ieee8023/covid-chestxray-dataset), trying to help medical personnel in filtering out possible COVID-19 cases using machine learning.

Thanks!

**Comment by ThisIsIsaac** [comment]
Answered in [this](https://github.com/ThisIsIsaac/Data-Science-for-COVID-19/issues/15#issuecomment-636754824) issue. Thanks!
