### ISSUE TITLE
Clinical data from EMRs

### ISSUE THREAD

**Issue by rkamaleswaran** [ThisIsIsaac/COVID-19_Korea_Dataset#15]
**Please describe the dataset you want**
Is it possible to get a public dataset of clinical data, such as vitals, labs, medication, etc. from hospitalized patients, similar to what is currently offered in MIMIC-III or eICU?

**How is it relevant to Covid-19?**
This may aid in phenotyping severity among hospitalized patients, including developing models to predict ventilator support, etc.

**Please add details that we would need to gather the data**
https://mimic.physionet.org/ - a similar data like what is offered here would be immensely useful if it is related specifically to COVID-19 patients

**Comment by ThisIsIsaac** [comment]
We have gotten lots of such requests, and we are still talking with Korean CDC to disclose such pertinent lab data. However, it is very unlikely that we will be able to incorporate such data in our dataset.
