### ISSUE TITLE
Updated Dataset

### ISSUE THREAD

**Issue by just2610** [ThisIsIsaac/COVID-19_Korea_Dataset#16]
**Please describe the dataset you want**
Looking for an updated dataset. 

**How is it relevant to Covid-19?**
There will be further updates on the individual cases, especially for recovery or other outcomes. This data/distribution is useful as input into the development of covid19 in other countries/future date.

**Please add details that we would need to gather the data**
Current data set is a good base. If possible, co-morbidities, treatment protocols, viral loads would be nice to have.

**Comment by ThisIsIsaac** [comment]
I am sorry for the delayed response. For an internal issue, we aren't able to update the githup repository. However, you can find the updated version of the same dataset at [our kaggle](https://www.kaggle.com/kimjihoo/coronavirusdataset).
