### ISSUE TITLE
Metadata Update

### ISSUE THREAD

**Issue by reeshmabijosh** [ThisIsIsaac/COVID-19_Korea_Dataset#19]
Hello,
Your dataset was added to CoronaWhy (https://www.coronawhy.org/) Data Lake on Dataverse as a piece of common COVID-19 data frame http://datasets.coronawhy.org/dataset.xhtml?persistentId=doi:10.5072/FK2/F64JFF
Would you be willing to help with the maintenance of your dataset in Dataverse, e.g. adding the relevant metadata and keeping the dataset up-to-date? That will help to make the dataset findable and accessible for the medical science community.

**Comment by ThisIsIsaac** [comment]
Hey @reeshmabijosh ,

Thanks so much 👍  And we'd love to! 

@jihoo-kim What do Would it be feasible for us to maintain all 3 repos: Github, Kaggle, and Dataverse

**Comment by ThisIsIsaac** [comment]
We'll keep Dataverse updated (although probably not within the next couple update cycles). Thanks @reeshmabijosh

**Comment by reeshmabijosh** [comment]
Hello, Isaac

Great,  thanks for your willingness to contribute.
 Please register in CoronaWhy Dataverse https://datasets.coronawhy.org/ and
I’ll give you the necessary permissions for editing your dataset.
Then please add relevant metadata - description and keywords to your
dataset.”

Thanks
Reeshma K
