### ISSUE TITLE
Where to find the latest dataset

### ISSUE THREAD

**Issue by SDSTony** [ThisIsIsaac/COVID-19_Korea_Dataset#23]
**Please describe the dataset you want**
안녕하세요. 데이터 구축해주셔서 감사합니다. 연구용으로 가장 최근까지 (11월) 업데이트 된 데이터를 찾고자 하는데, 어디서 얻을 수 있을지 궁금합니다. 

**How is it relevant to Covid-19?**
지역 별 코로나 발생 예측 모델을 구축해, 지역별 거리두기가 지켜져 있는 정도를 간접적으로 추정하고자 합니다. 또한 구축 과정을 공개하여 데이터 사이언스 생태계 확대에 기여하고자 합니다. 

**Please add details that we would need to gather the data**

**Comment by ThisIsIsaac** [comment]
죄송하게도 현재는 업데이트를 중단하였습니다. 관심 가져주셔서 감사합니다 :)
