### ISSUE TITLE
Request for patients contact dataset

### ISSUE THREAD

**Issue by Jebrankhan** [ThisIsIsaac/COVID-19_Korea_Dataset#24]
Hello!

I am a Ph.D. student at Korea Aerospace University. I am currently working on a project related to Covid-19.

I was searching for patients' contact network datasets and found your dataset interesting.

However, there are many missing links in the dataset. The datasets do not have information about who got the disease from who.

I want to know about is this information available in any other dataset? If you have any knowledge about that, please let me know. Or if you have extended this dataset and populated some of the missing information please provide it to me if possible.

**Comment by ThisIsIsaac** [comment]
Thanks for your interest :) Unfortunately, that's all we have on the network data.
