### ISSUE TITLE
Need clarification on patient routes dataset

### ISSUE THREAD

**Issue by piyush-bagad** [ThisIsIsaac/COVID-19_Korea_Dataset#3]
**Please describe the dataset you want**
We need clarifications on what some of the features mean in `routes.csv` dataset. For example, what does `local_id` and `global_id` mean? What does one particular row mean?

**How is it relevant to Covid-19?**
We want to do more analysis on the routes dataset.

**Comment by minty99** [comment]
`global_id` means the official numbering by Korea Centers for Disease Control and Prevention (KCDC).
`local_id` means the number from local government; for example, `seoul_1` means the patient is first one in Seoul.

We will add more detailed description as soon as possible.
