### ISSUE TITLE
Data hasn't been updated here in the last eight days, and to Kaggle in four days.

### ISSUE THREAD

**Issue by sangwon-hyun** [ThisIsIsaac/COVID-19_Korea_Dataset#9]
Please provide the up-to-date data so that researchers (including me) can work with the latest information for modeling and prediction?

**Comment by ThisIsIsaac** [comment]
Yes, I completely agree with you on the importance of up-to-date data, and it is our one of the top priorities. I don't want to make any promises, but we will likely catchup with all the patient details early next week, and from then on, updates will be much more frequent.

**Comment by sangwon-hyun** [comment]
Another gentle reminder!

**Comment by sangwon-hyun** [comment]
Okay I'm guessing this repository is defunct. If anyone else knows of alternative data sources, please reply.

**Comment by ThisIsIsaac** [comment]
I am sorry for the delayed response. For an internal issue, we aren't able to update the githup repository. However, you can find the updated version of the same dataset at [our kaggle](https://www.kaggle.com/kimjihoo/coronavirusdataset) .
